name: peaceful
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/image/

  fonts:
    - family: Quicksand-Bold
      fonts:
        - asset: asset/font/Quicksand-Bold.ttf
    
    - family: Quicksand-Light
      fonts:
        - asset: asset/font/Quicksand-Light.ttf
    
    - family: Quicksand-Medium
      fonts:
        - asset: asset/font/Quicksand-Medium.ttf
    
    - family: Quicksand-Regular
      fonts:
        - asset: asset/font/Quicksand-Regular.ttf
    
    - family: Quicksand-Semibold
      fonts:
        - asset: asset/font/Quicksand-Semibold.ttf
